In [1]:
import numpy as np
import pandas as pd
import os
os.chdir('D:\\RIYA\\college stuff\\ML with python')
os.getcwd()

'D:\\RIYA\\college stuff\\ML with python'

In [3]:
dataset = pd.read_csv('petrol_consumption.csv')
dataset

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.00            3571            1976                         0.525   
1         9.00            4092            1250                         0.572   
2         9.00            3865            1586                         0.580   
3         7.50            4870            2351                         0.529   
4         8.00            4399             431                         0.544   
5        10.00            5342            1333                         0.571   
6         8.00            5319           11868                         0.451   
7         8.00            5126            2138                         0.553   
8         8.00            4447            8577                         0.529   
9         7.00            4512            8507                         0.552   
10        8.00            4391            5939                         0.530   
11        7.50            5126           14186                         0.525   
12        7.00            4817            6930                         0.574   
13        7.00            4207            6580                         0.545   
14        7.00            4332            8159                         0.608   
15        7.00            4318           10340                         0.586   
16        7.00            4206            8508                         0.572   
17        7.00            3718            4725                         0.540   
18        7.00            4716            5915                         0.724   
19        8.50            4341            6010                         0.677   
20        7.00            4593            7834                         0.663   
21        8.00            4983             602                         0.602   
22        9.00            4897            2449                         0.511   
23        9.00            4258            4686                         0.517   
24        8.50            4574            2619                         0.551   
25        9.00            3721            4746                         0.544   
26        8.00            3448            5399                         0.548   
27        7.50            3846            9061                         0.579   
28        8.00            4188            5975                         0.563   
29        9.00            3601            4650                         0.493   
30        7.00            3640            6905                         0.518   
31        7.00            3333            6594                         0.513   
32        8.00            3063            6524                         0.578   
33        7.50            3357            4121                         0.547   
34        8.00            3528            3495                         0.487   
35        6.58            3802            7834                         0.629   
36        5.00            4045           17782                         0.566   
37        7.00            3897            6385                         0.586   
38        8.50            3635            3274                         0.663   
39        7.00            4345            3905                         0.672   
40        7.00            4449            4639                         0.626   
41        7.00            3656            3985                         0.563   
42        7.00            4300            3635                         0.603   
43        7.00            3745            2611                         0.508   
44        6.00            5215            2302                         0.672   
45        9.00            4476            3942                         0.571   
46        7.00            4296            4083                         0.623   
47        7.00            5002            9794                         0.593   

    Petrol_Consumption  
0                  541  
1                  524  
2       

In [4]:
X = dataset.iloc[:,0:4].values
X

array([[9.0000e+00, 3.5710e+03, 1.9760e+03, 5.2500e-01],
       [9.0000e+00, 4.0920e+03, 1.2500e+03, 5.7200e-01],
       [9.0000e+00, 3.8650e+03, 1.5860e+03, 5.8000e-01],
       [7.5000e+00, 4.8700e+03, 2.3510e+03, 5.2900e-01],
       [8.0000e+00, 4.3990e+03, 4.3100e+02, 5.4400e-01],
       [1.0000e+01, 5.3420e+03, 1.3330e+03, 5.7100e-01],
       [8.0000e+00, 5.3190e+03, 1.1868e+04, 4.5100e-01],
       [8.0000e+00, 5.1260e+03, 2.1380e+03, 5.5300e-01],
       [8.0000e+00, 4.4470e+03, 8.5770e+03, 5.2900e-01],
       [7.0000e+00, 4.5120e+03, 8.5070e+03, 5.5200e-01],
       [8.0000e+00, 4.3910e+03, 5.9390e+03, 5.3000e-01],
       [7.5000e+00, 5.1260e+03, 1.4186e+04, 5.2500e-01],
       [7.0000e+00, 4.8170e+03, 6.9300e+03, 5.7400e-01],
       [7.0000e+00, 4.2070e+03, 6.5800e+03, 5.4500e-01],
       [7.0000e+00, 4.3320e+03, 8.1590e+03, 6.0800e-01],
       [7.0000e+00, 4.3180e+03, 1.0340e+04, 5.8600e-01],
       [7.0000e+00, 4.2060e+03, 8.5080e+03, 5.7200e-01],
       [7.0000e+00, 3.7180e+03,

In [5]:
y = dataset.iloc[:,4].values
y

array([541, 524, 561, 414, 410, 457, 344, 467, 464, 498, 580, 471, 525,
       508, 566, 635, 603, 714, 865, 640, 649, 540, 464, 547, 460, 566,
       577, 631, 574, 534, 571, 554, 577, 628, 487, 644, 640, 704, 648,
       968, 587, 699, 632, 591, 782, 510, 610, 524], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)
print(X_train.shape)
print(X_test.shape)

(38, 4)
(10, 4)


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_test)

[[9.000e+00 3.601e+03 4.650e+03 4.930e-01]
 [8.000e+00 4.399e+03 4.310e+02 5.440e-01]
 [8.000e+00 3.448e+03 5.399e+03 5.480e-01]
 [7.000e+00 3.640e+03 6.905e+03 5.180e-01]
 [8.000e+00 3.063e+03 6.524e+03 5.780e-01]
 [7.000e+00 3.897e+03 6.385e+03 5.860e-01]
 [8.000e+00 3.528e+03 3.495e+03 4.870e-01]
 [7.000e+00 4.449e+03 4.639e+03 6.260e-01]
 [8.000e+00 5.126e+03 2.138e+03 5.530e-01]
 [8.000e+00 4.391e+03 5.939e+03 5.300e-01]]


In [11]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 20,random_state=0)
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)
print(y_pred)

[506.1 506.1 506.1 506.1 506.1 506.1 506.1 506.1 506.1 506.1]


In [10]:
from sklearn import metrics
mar = metrics.mean_absolute_error(y_test,y_pred)
print('Mean Absolute Error:',metrics.mean_absolute_error(y_test,y_pred))
print('Root Mean Absolute Error:',np.sqrt(mar))

Mean Absolute Error: 74.16
Root Mean Absolute Error: 8.611620056644394


In [12]:
from sklearn.metrics import r2_score


In [16]:
r2 = r2_score(y_test,y_pred)
print(r2)

-0.31997767704763524
