In [1]:
import pandas as pd
import os


In [2]:
os.chdir('D:\\RIYA\\college stuff\\ML with python')
print (os.getcwd())

 
df = pd.read_csv("College.csv")
print (df)



D:\RIYA\college stuff\ML with python
    Private   Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
0       Yes   1660    1232     721         23         52         2885   
1       Yes   2186    1924     512         16         29         2683   
2       Yes   1428    1097     336         22         50         1036   
3       Yes    417     349     137         60         89          510   
4       Yes    193     146      55         16         44          249   
..      ...    ...     ...     ...        ...        ...          ...   
772      No   2197    1515     543          4         26         3089   
773     Yes   1959    1805     695         24         47         2849   
774     Yes   2097    1915     695         34         61         2793   
775     Yes  10705    2453    1317         95         99         5217   
776     Yes   2989    1855     691         28         63         2988   

     P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0           

In [3]:
print (df.shape)
print (df.columns)



(777, 18)
Index(['Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'],
      dtype='object')


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values

# Encode label category  male -> 1 and  female -> 0

target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train.shape)


(621, 17)


In [5]:
from sklearn.svm import LinearSVC,SVC
classifier = LinearSVC()


classifier.fit(X_train,y_train)

y_predict = classifier.predict(X_test)

print (classifier.score(X_test,y_test))



0.7564102564102564


C:\Python3.10\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [6]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_predict,y_test))


[[39 38]
 [ 0 79]]


In [7]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )


0.7564102564102564


In [8]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))



              precision    recall  f1-score   support

           0       0.51      1.00      0.67        39
           1       1.00      0.68      0.81       117

    accuracy                           0.76       156
   macro avg       0.75      0.84      0.74       156
weighted avg       0.88      0.76      0.77       156



In [9]:
classifier = SVC(kernel='linear')
classifier.fit(X_train,y_train)
classifier.score(X_test,y_test)


0.9423076923076923

In [10]:
y_predict = classifier.predict(X_test)
print(confusion_matrix(y_predict,y_test))
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )
print(classification_report(y_test, y_predict))



[[ 33   3]
 [  6 114]]
0.9423076923076923
              precision    recall  f1-score   support

           0       0.92      0.85      0.88        39
           1       0.95      0.97      0.96       117

    accuracy                           0.94       156
   macro avg       0.93      0.91      0.92       156
weighted avg       0.94      0.94      0.94       156



In [11]:
classifier = SVC()
classifier.fit(X_train,y_train)
classifier.score(X_test,y_test)


0.9230769230769231

In [12]:
y_predict = classifier.predict(X_test)
print(confusion_matrix(y_predict,y_test))
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )
print(classification_report(y_test, y_predict))



[[ 33   6]
 [  6 111]]
0.9230769230769231
              precision    recall  f1-score   support

           0       0.85      0.85      0.85        39
           1       0.95      0.95      0.95       117

    accuracy                           0.92       156
   macro avg       0.90      0.90      0.90       156
weighted avg       0.92      0.92      0.92       156



In [13]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler



In [14]:
scaler = StandardScaler()
X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values
X = scaler.fit_transform(X)


In [15]:
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train.shape)


(621, 17)


In [16]:
classifier = SVC()
classifier.fit(X_train,y_train)
classifier.score(X_test,y_test)


0.9423076923076923

In [17]:
y_predict = classifier.predict(X_test)
print(confusion_matrix(y_predict,y_test))
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )
print(classification_report(y_test, y_predict))


[[ 32   2]
 [  7 115]]
0.9423076923076923
              precision    recall  f1-score   support

           0       0.94      0.82      0.88        39
           1       0.94      0.98      0.96       117

    accuracy                           0.94       156
   macro avg       0.94      0.90      0.92       156
weighted avg       0.94      0.94      0.94       156



In [18]:
import numpy as np

C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)
param_grid = dict( gamma=gamma_range,C=C_range)
grid = GridSearchCV(SVC(), param_grid=param_grid,verbose=2)
grid.fit(X_train, y_train)


Fitting 5 folds for each of 169 candidates, totalling 845 fits
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-07; total time=   0.0s
[CV] END ................................C=0.0

GridSearchCV(estimator=SVC(),
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05,
       1.e+06, 1.e+07, 1.e+08, 1.e+09, 1.e+10]),
                         'gamma': array([1.e-09, 1.e-08, 1.e-07, 1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02,
       1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])},
             verbose=2)

In [19]:
print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))


The best parameters are {'C': 1000000.0, 'gamma': 1e-07} with a score of 0.94


In [20]:

y_predict = grid.predict(X_test)
print(confusion_matrix(y_predict,y_test))
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )
print(classification_report(y_test, y_predict))


[[ 33   3]
 [  6 114]]
0.9423076923076923
              precision    recall  f1-score   support

           0       0.92      0.85      0.88        39
           1       0.95      0.97      0.96       117

    accuracy                           0.94       156
   macro avg       0.93      0.91      0.92       156
weighted avg       0.94      0.94      0.94       156



In [21]:
params = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]}
print (params)
rgrid =  RandomizedSearchCV(SVC(), param_distributions=params, n_iter= 12,cv = 10,  verbose=2 )

rgrid.fit(X_train, y_train)


{'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001]}
Fitting 10 folds for each of 12 candidates, totalling 120 fits
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=1, gamma=0.1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total ti

RandomizedSearchCV(cv=10, estimator=SVC(), n_iter=12,
                   param_distributions={'C': [0.1, 1, 10, 100],
                                        'gamma': [1, 0.1, 0.01, 0.001]},
                   verbose=2)

In [22]:
print("The best parameters are %s with a score of %0.2f"
      % (rgrid.best_params_, rgrid.best_score_))


The best parameters are {'gamma': 0.01, 'C': 10} with a score of 0.94


In [23]:
y_predict = rgrid.predict(X_test)
print(confusion_matrix(y_predict,y_test))
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )
print(classification_report(y_test, y_predict))


[[ 35   2]
 [  4 115]]
0.9615384615384616
              precision    recall  f1-score   support

           0       0.95      0.90      0.92        39
           1       0.97      0.98      0.97       117

    accuracy                           0.96       156
   macro avg       0.96      0.94      0.95       156
weighted avg       0.96      0.96      0.96       156

